"""Heliax: a performance-first tensor and neural network library for Python."""

from . import autograd, backend, data, functional, nn, optim, profiler, quantization, serialization
from .autograd import gradcheck
from .backend import available_backends, backend_info, get_backend, set_backend
from .data import DataLoader, TensorDataset, fit, seed_everything
from .functional import (
    binary_cross_entropy,
    clip,
    concatenate,
    cross_entropy,
    dropout,
    embedding,
    gelu,
    log_softmax,
    mean_absolute_error,
    mean_squared_error,
    relu,
    sigmoid,
    silu,
    softmax,
    stack,
    tanh,
)
from .nn import (
    GELU,
    MLP,
    Conv2d,
    Dropout,
    Embedding,
    Flatten,
    LayerNorm,
    Linear,
    LogSoftmax,
    Module,
    MultiheadAttention,
    ReLU,
    Sequential,
    Sigmoid,
    SiLU,
    Softmax,
    Tanh,
)
from .optim import SGD, Adam, AdamW, CosineAnnealingLR, RMSProp, StepLR, clip_grad_norm_
from .profiler import ProfileResult, count_parameters, profile
from .quantization import (
    QuantizedTensor,
    compression_ratio,
    dequantize,
    dequantize_state_dict,
    quantize,
    quantize_state_dict,
)
from .serialization import load_checkpoint, load_state_dict, save_checkpoint, save_state_dict
from .tensor import (
    Parameter,
    Tensor,
    arange,
    enable_grad,
    from_numpy,
    full,
    is_grad_enabled,
    no_grad,
    ones,
    randn,
    tensor,
    zeros,
)

__version__ = "0.1.0"

__all__ = [
    "GELU",
    "MLP",
    "SGD",
    "Adam",
    "AdamW",
    "Conv2d",
    "CosineAnnealingLR",
    "DataLoader",
    "Dropout",
    "Embedding",
    "Flatten",
    "LayerNorm",
    "Linear",
    "LogSoftmax",
    "Module",
    "MultiheadAttention",
    "Parameter",
    "ProfileResult",
    "QuantizedTensor",
    "RMSProp",
    "ReLU",
    "Sequential",
    "SiLU",
    "Sigmoid",
    "Softmax",
    "StepLR",
    "Tanh",
    "Tensor",
    "TensorDataset",
    "arange",
    "autograd",
    "available_backends",
    "backend",
    "backend_info",
    "binary_cross_entropy",
    "clip",
    "clip_grad_norm_",
    "compression_ratio",
    "concatenate",
    "count_parameters",
    "cross_entropy",
    "data",
    "dequantize",
    "dequantize_state_dict",
    "dropout",
    "embedding",
    "enable_grad",
    "fit",
    "from_numpy",
    "full",
    "functional",
    "gelu",
    "get_backend",
    "gradcheck",
    "is_grad_enabled",
    "load_checkpoint",
    "load_state_dict",
    "log_softmax",
    "mean_absolute_error",
    "mean_squared_error",
    "nn",
    "no_grad",
    "ones",
    "optim",
    "profile",
    "profiler",
    "quantization",
    "quantize",
    "quantize_state_dict",
    "randn",
    "relu",
    "save_checkpoint",
    "save_state_dict",
    "seed_everything",
    "serialization",
    "set_backend",
    "sigmoid",
    "silu",
    "softmax",
    "stack",
    "tanh",
    "tensor",
    "zeros",
]
